package ExampleLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAnotherConcept = createDescriptorForAnotherConcept();
  /*package*/ final ConceptDescriptor myConceptTestConcept = createDescriptorForTestConcept();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAnotherConcept, myConceptTestConcept);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AnotherConcept:
        return myConceptAnotherConcept;
      case LanguageConceptSwitch.TestConcept:
        return myConceptTestConcept;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAnotherConcept() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ExampleLanguage", "AnotherConcept", 0xbec5bd5e19f44b9cL, 0x855774df5de1c0e0L, 0x434e9d83ea41bb4dL);
    b.class_(false, false, true);
    b.origin("r:854bd2fe-1d3d-486b-9e78-c1025440a6ad(ExampleLanguage.structure)/4849987038621055821");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTestConcept() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ExampleLanguage", "TestConcept", 0xbec5bd5e19f44b9cL, 0x855774df5de1c0e0L, 0x434e9d83ea401b8fL);
    b.class_(false, false, true);
    b.origin("r:854bd2fe-1d3d-486b-9e78-c1025440a6ad(ExampleLanguage.structure)/4849987038620949391");
    b.version(3);
    b.associate("testReference", 0x434e9d83ea41bdd9L).target(0xbec5bd5e19f44b9cL, 0x855774df5de1c0e0L, 0x434e9d83ea41bb4dL).optional(true).origin("4849987038621056473").done();
    return b.create();
  }
}
